name: Style check
permissions: {}

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  style-check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install -U clang-format==18.* yapf==0.43.* nbformat==5.10.* pydocstyle==6.0.0
      - name: Run style check
        run: |
          python ci/check_style.py --verbose
      - name: Run docstring style check
        run: |
          pydocstyle --convention=google --add-ignore=D1,D205,D415,D212 .
