openyolo3d:
  frequency: 1
  vis_depth_threshold: 0.4
  depth_scale: 6553.5
  topk: 40
  topk_per_image: -1

network2d:
  text_prompts: ["basket", "bed", "bench", "bin", "blanket", "blinds", "book", "bottle", "box", "bowl", "camera", "cabinet", "candle", "chair", "clock", "cloth", "comforter", "cushion", "desk", "desk-organizer", "door", "indoor-plant", "lamp", "monitor", "nightstand", "panel", "picture", "pillar", "pillow", "pipe", "plant-stand", "plate", "pot", "sculpture", "shelf", "sofa", "stool", "switch", "table", "tablet", "tissue-paper", "tv-screen", "tv-stand", "vase", "vent", "wall-plug", "window", "rug"]
  topk: 100
  th: 0.1
  nms: 0.3
  use_amp: False
  pretrained_path: "pretrained/checkpoints/yolo_world_v2_x_obj365v1_goldg_cc3mlite_pretrain_1280ft-14996a36.pth"
  config_path: "pretrained/configs/yolo_world_v2_x_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py"

network3d:
  pretrained_path: "pretrained/checkpoints/scannet200_val.ckpt"
  th: 0.02
  nms: 0.1
  is_gt: False
